version: "3.9"
services:
 web:
  build:
   context: ..
   dockerfile: ./docker/Dockerfile
  ports:
   - "3000:5173"
  volumes:
    - ./src:/app/src
    - ./public:/app/public
    - ./vite.config.ts:/app/vite.config.ts
    - ./package-lock.json:/app/package-lock.json
  environment:
   - VITE_MODE=development
   - VITE_PRODUCTION=false
